ci: Add docker build step

diff --git a/.github/workflows/integration_test.yml b/.github/workflows/integration_test.yml
--- a/.github/workflows/integration_test.yml
+++ b/.github/workflows/integration_test.yml
@@ -1,4 +1,4 @@
-name: Integration Tests
+name: Docker Workflows
 
 on:
   push:
@@ -8,9 +8,52 @@ on:
   pull_request:
 
 jobs:
-  docker-compose:
+  image-build:
     runs-on: ubuntu-latest
 
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      # - name: "Set up Python"
+      #   uses: actions/setup-python@v5
+      #   with:
+      #     python-version-file: "pyproject.toml"
+      # - name: Install uv
+      #   uses: astral-sh/setup-uv@v6
+      #   with:
+      #     enable-cache: true
+      # - name: Install the project
+      #   run: uv sync --locked --all-extras --dev
+
+      # - name: Build tarxiv base image
+      #   run: |
+      #     cd setup
+      #     docker compose build tarxiv-api
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Build and push Docker image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          file: Dockerfile
+          push: true
+          tags: |
+            ghcr.io/${{ github.repository_owner }}/tarxiv:${{ github.sha }} 
+            ghcr.io/${{ github.repository_owner }}/tarxiv:latest
+
+  compose-integration-tests:
+    runs-on: ubuntu-latest
+    needs: image-build
+    env:
+      TARXIV_PORT: 9001
     steps:
       - uses: actions/checkout@v4
       - name: "Set up Python"
@@ -41,6 +84,8 @@ jobs:
           uv run --env-file setup/.env scripts/db_utils.py -l -f setup/example_dataset.json
       - name: Build tarxiv API image
         run: |
+          # Build tarxiv image from local compose setup
+          # TODO: should use the image built in the previous job
           cd setup
           docker compose build tarxiv-api
       - name: Start tarxiv API
@@ -49,13 +94,18 @@ jobs:
           docker compose up -d tarxiv-api
           sleep 20
           docker ps -a
-          # curl -f http://localhost:9001/
+          docker logs tarxiv-api
       - name: Start dashboard
         run: |
           cd setup
           docker compose up -d tarxiv-dashboard
           sleep 10
           docker ps -a
+          docker logs tarxiv-dashboard
+      - name: Ping API to check it's up
+        run: |
+          # This currently fails as the API startup is not working properly in CI 
+          curl -f http://localhost:${{ env.TARXIV_PORT }}/ || exit 1
       - name: Teardown compose environment
         if: always()
         run: |
